version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: >
      bash -c '
      bin/elasticsearch-keystore create;
      echo "your_password" | bin/elasticsearch-keystore add -x "bootstrap.password";
      sleep 5;
      curl -XPOST -u "elastic:your_password" "http://elasticsearch:9200/_security/role/admin_role" -H "Content-Type: application/json" -d "{\"cluster\":[\"all\"],\"indices\":[{\"names\":[\"*\"],\"privileges\":[\"all\"]}]}";
      curl -XPOST -u "elastic:your_password" "http://elasticsearch:9200/_security/user/admin" -H "Content-Type: application/json" -d "{\"password\":\"admin_password\",\"roles\":[\"admin_role\"]}";
      bin/elasticsearch
      '

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200

volumes:
  esdata:
